"""Default safe-copy policy for Claw Keeper."""

DEFAULT_BRANCH = "raw-history"
POLICY_VERSION = 3

# Include paths are relative to the configured source path. For the default
# OpenClaw layout, source should usually be ~/.openclaw. These are broad on
# purpose: the mirror classifier decides which files inside them are safe.
DEFAULT_INCLUDE_PATHS = (
    "workspace/",
    "identity/",
    "memory/",
    "agents/",
    "flows/",
    "tasks/",
    "plugin-skills/",
    "skills/",
    "openclaw.json",
)

NARROW_TEXT_INCLUDE_PATHS = (
    "workspace/",
    "plugin-skills/",
    "skills/",
    "openclaw.json",
)

LEGACY_BROAD_INCLUDE_PATHS = DEFAULT_INCLUDE_PATHS

DEFAULT_PRUNE_PATHS = ()

DEFAULT_MAX_TEXT_FILE_BYTES = 512 * 1024

DEFAULT_TEXT_EXTENSIONS = (
    ".cfg",
    ".conf",
    ".css",
    ".csv",
    ".html",
    ".ini",
    ".js",
    ".json",
    ".jsonl",
    ".jsx",
    ".lock",
    ".md",
    ".mjs",
    ".py",
    ".sh",
    ".toml",
    ".ts",
    ".tsx",
    ".txt",
    ".xml",
    ".yaml",
    ".yml",
)

DEFAULT_TEXT_FILENAMES = (
    ".gitignore",
    "AGENTS",
    "HEARTBEAT",
    "IDENTITY",
    "SKILL",
    "SOUL",
    "TOOLS",
    "USER",
)

DEFAULT_EXCLUDE_PATTERNS = (
    ".git/",
    ".pytest_cache/",
    ".uv-cache/",
    ".venv/",
    ".env",
    "__pycache__/",
    "auth*",
    "browser/",
    "cache/",
    "codex-home/",
    "completions/",
    "credentials*",
    "devices/",
    "goals_*.sqlite*",
    "identity/device-auth.json",
    "logs/",
    "node_modules/",
    "npm/",
    "oauth*",
    "plugins/cache/",
    "profiles/",
    "provider-credentials/",
    "secrets/",
    "sessions/",
    "shell_snapshots/",
    "state_*.sqlite*",
    "tmp/",
    "tokens*",
    "*.pem",
    "*.key",
    "*.sqlite",
    "*.sqlite-*",
    "*.sqlite-shm",
    "*.sqlite-wal",
    "*.db",
    "*.db-*",
    "*.db-shm",
    "*.db-wal",
    "*.shm",
    "*.wal",
    "*API_KEY*",
    "*access_token*",
    "*api_key*",
    "*auth*",
    "*bot_token*",
    "*credential*",
    "*oauth*",
    "*refresh_token*",
    "*secret*",
    "*token*",
    "id_ed25519",
    "id_rsa",
    "installation_id",
    "openclaw.json.bak*",
    "openclaw.json.last-good",
    "update-check.json",
    "gateway-supervisor-restart-handoff.json",
)

DEFAULT_GITIGNORE_LINES = (
    ".claw-keeper/",
    ".git/",
    ".pytest_cache/",
    ".uv-cache/",
    ".venv/",
    ".env",
    "__pycache__/",
    "auth*",
    "browser/",
    "cache/",
    "codex-home/",
    "completions/",
    "credentials*",
    "devices/",
    "goals_*.sqlite*",
    "identity/device-auth.json",
    "logs/",
    "node_modules/",
    "npm/",
    "oauth*",
    "plugins/cache/",
    "profiles/",
    "provider-credentials/",
    "secrets/",
    "sessions/",
    "shell_snapshots/",
    "state_*.sqlite*",
    "tmp/",
    "tokens*",
    "*.pem",
    "*.key",
    "*.sqlite",
    "*.sqlite-*",
    "*.sqlite-shm",
    "*.sqlite-wal",
    "*.db",
    "*.db-*",
    "*.db-shm",
    "*.db-wal",
    "*.shm",
    "*.wal",
    "*API_KEY*",
    "*access_token*",
    "*api_key*",
    "*auth*",
    "*bot_token*",
    "*credential*",
    "*oauth*",
    "*refresh_token*",
    "*secret*",
    "*token*",
    "id_ed25519",
    "id_rsa",
    "installation_id",
)
